content:
  - name: poetry
    label: Poetry
    path: _poetry
    type: collection
    filename: "{slug}.md"
    exclude:
      - index.md
    fields:
      - name: title
        label: Title
        type: text

      - name: author
        label: Author
        type: text
        default: Anshuman3kdka
        hidden: true

      - name: body
        label: Poem
        type: markdown

  - name: prose
    label: Prose
    path: _prose
    type: collection
    filename: "{slug}.md"
    exclude:
      - index.md
    fields:
      - name: title
        label: Title

      - name: author
        type: text
        default: Anshuman3kdka
        hidden: true

      - name: body
        label: Prose
        type: markdown

  - name: essays
    label: Essays
    path: _essays
    type: collection
    filename: "{slug}.md"
    exclude:
      - index.md
    fields:
      - name: title
        label: Title

      - name: author
        type: text
        default: Anshuman3kdka
        hidden: true

      - name: body
        label: Essay
        type: markdown

  - name: projects
    label: Projects
    path: _projects
    type: collection
    filename: "{slug}.md"
    exclude:
      - index.md
    fields:
      - name: title
        label: Project Title
      - name: body
        label: Description
        type: markdown

  - name: achievements
    label: Achievements
    path: _achievements
    type: collection
    filename: "{slug}.md"
    exclude:
      - index.md
    fields:
      - name: title
        label: Achievement
      - name: body
        label: Details
        type: markdown
