content:
  - name: poetry
    label: Poetry
    path: poetry
    type: collection
    filename: "{slug}.md"
    fields:
      - name: title
        label: Title
        type: text
      - name: body
        label: Poem
        type: markdown

  - name: prose
    label: Prose
    path: prose
    type: collection
    filename: "{slug}.md"
    fields:
      - name: title
        label: Title
        type: text
      - name: body
        label: Prose
        type: markdown

  - name: essays
    label: Essays
    path: essays
    type: collection
    filename: "{slug}.md"
    fields:
      - name: title
        label: Title
        type: text
      - name: body
        label: Essay
        type: markdown

  - name: projects
    label: Projects
    path: projects
    type: collection
    filename: "{slug}.md"
    fields:
      - name: title
        label: Project Title
        type: text
      - name: body
        label: Description
        type: markdown

  - name: achievements
    label: Achievements
    path: achievements
    type: collection
    filename: "{slug}.md"
    fields:
      - name: title
        label: Achievement
        type: text
      - name: body
        label: Details
        type: markdown
