media:
  input: assets/uploads
  output: /assets/uploads

content:
  - name: poetry
    label: Poetry
    path: poetry
    type: collection
    filename: "{slug}.md"
    exclude:
      - index.md
    fields:
      - name: title
        label: Title
        type: text
        required: true
      - name: author
        label: Author
        type: text
        default: Anshuman3kdka
        hidden: true
      - name: eyebrow
        label: Eyebrow Text (optional)
        type: text
        required: false
      - name: description
        label: SEO Description (optional)
        type: text
        required: false
      - name: featured_image
        label: Featured Image (optional)
        type: image
        required: false
      - name: body
        label: Poem
        type: markdown

  - name: prose
    label: Prose
    path: prose
    type: collection
    filename: "{slug}.md"
    exclude:
      - index.md
    fields:
      - name: title
        label: Title
        type: text
        required: true
      - name: author
        type: text
        default: Anshuman3kdka
        hidden: true
      - name: eyebrow
        label: Eyebrow Text (optional)
        type: text
        required: false
      - name: description
        label: SEO Description (optional)
        type: text
        required: false
      - name: featured_image
        label: Featured Image (optional)
        type: image
        required: false
      - name: body
        label: Prose
        type: markdown

  - name: essays
    label: Essays
    path: essays
    type: collection
    filename: "{slug}.md"
    exclude:
      - index.md
    fields:
      - name: title
        label: Title
        type: text
        required: true
      - name: author
        type: text
        default: Anshuman3kdka
        hidden: true
      - name: eyebrow
        label: Eyebrow Text (optional)
        type: text
        required: false
      - name: description
        label: SEO Description (optional)
        type: text
        required: false
      - name: featured_image
        label: Featured Image (optional)
        type: image
        required: false
      - name: body
        label: Essay
        type: markdown

  - name: projects
    label: Projects
    path: projects
    type: collection
    filename: "{slug}.md"
    exclude:
      - index.md
    fields:
      - name: title
        label: Project Title
        type: text
        required: true
      - name: eyebrow
        label: Eyebrow Text (optional)
        type: text
        required: false
      - name: description
        label: SEO Description (optional)
        type: text
        required: false
      - name: image
        label: Project Image (optional)
        type: image
        required: false
      - name: body
        label: Description
        type: markdown

  - name: achievements
    label: Achievements
    path: achievements
    type: collection
    filename: "{slug}.md"
    exclude:
      - index.md
    fields:
      - name: title
        label: Achievement
        type: text
        required: true
      - name: eyebrow
        label: Eyebrow Text (optional)
        type: text
        required: false
      - name: description
        label: SEO Description (optional)
        type: text
        required: false
      - name: image
        label: Image (optional)
        type: image
        required: false
      - name: body
        label: Details
        type: markdown

  - name: landing_home
    label: Landing Home (index.md)
    path: index.md
    type: file
    fields:
      - name: title
        label: Page Title (optional)
        type: text
        required: false
      - name: description
        label: SEO Description (optional)
        type: text
        required: false
      - name: body
        label: Home Sections
        type: markdown

  - name: about_page
    label: About Page
    path: about/index.md
    type: file
    fields:
      - name: title
        label: Page Title
        type: text
        required: true
      - name: description
        label: SEO Description (optional)
        type: text
        required: false
      - name: portrait_image
        label: About Portrait Image
        type: image
        required: false
      - name: portrait_alt
        label: About Portrait Alt Text
        type: text
        required: false
      - name: portrait_caption
        label: About Portrait Caption
        type: text
        required: false
      - name: body
        label: Content
        type: markdown

  - name: contact_page
    label: Contact Page
    path: contact/index.md
    type: file
    fields:
      - name: title
        label: Page Title
        type: text
        required: true
      - name: description
        label: SEO Description (optional)
        type: text
        required: false
      - name: body
        label: Content
        type: markdown

  - name: resume_page
    label: Resume Page
    path: resume/index.md
    type: file
    fields:
      - name: title
        label: Page Title
        type: text
        required: true
      - name: description
        label: SEO Description (optional)
        type: text
        required: false
      - name: body
        label: Content
        type: markdown

  - name: creative_page
    label: Creative Page
    path: creative/index.md
    type: file
    fields:
      - name: title
        label: Page Title
        type: text
        required: true
      - name: description
        label: SEO Description (optional)
        type: text
        required: false
      - name: body
        label: Content
        type: markdown

  - name: poetry_page
    label: Poetry Listing Page
    path: poetry/index.md
    type: file
    fields:
      - name: title
        label: Page Title
        type: text
        required: true
      - name: description
        label: SEO Description (optional)
        type: text
        required: false
      - name: body
        label: Content
        type: markdown

  - name: prose_page
    label: Prose Listing Page
    path: prose/index.md
    type: file
    fields:
      - name: title
        label: Page Title
        type: text
        required: true
      - name: description
        label: SEO Description (optional)
        type: text
        required: false
      - name: body
        label: Content
        type: markdown

  - name: essays_page
    label: Essays Listing Page
    path: essays/index.md
    type: file
    fields:
      - name: title
        label: Page Title
        type: text
        required: true
      - name: description
        label: SEO Description (optional)
        type: text
        required: false
      - name: body
        label: Content
        type: markdown

  - name: projects_page
    label: Projects Listing Page
    path: projects/index.md
    type: file
    fields:
      - name: title
        label: Page Title
        type: text
        required: true
      - name: description
        label: SEO Description (optional)
        type: text
        required: false
      - name: body
        label: Content
        type: markdown

  - name: achievements_page
    label: Achievements Listing Page
    path: achievements/index.md
    type: file
    fields:
      - name: title
        label: Page Title
        type: text
        required: true
      - name: description
        label: SEO Description (optional)
        type: text
        required: false
      - name: body
        label: Content
        type: markdown

  - name: secondary_home_page
    label: Secondary Home Page
    path: home/index.md
    type: file
    fields:
      - name: title
        label: Page Title
        type: text
        required: true
      - name: description
        label: SEO Description (optional)
        type: text
        required: false
      - name: body
        label: Content
        type: markdown

  - name: home_page_cards
    label: Home Page Cards
    path: _data/home_cards.yml
    type: file
    fields:
      - name: cards
        label: Homepage Cards
        type: object
        list: true
        addLabel: "+homepage card"
        required: false
        fields:
          - name: type
            label: Type of Card
            type: text
            required: true
          - name: title
            label: Card Title
            type: text
            required: true
          - name: description
            label: Card Description
            type: text
            required: true
          - name: link_text
            label: Link Text
            type: text
            required: true
          - name: link_url
            label: Link URL
            type: text
            required: true

  - name: site_settings
    label: Site Settings
    path: _data/site.yml
    type: file
    fields:
      - name: site_title
        label: Site Title
        type: text
        required: true
      - name: site_tagline
        label: Site Tagline
        type: text
        required: false
      - name: site_description
        label: Default SEO Description
        type: text
        required: false
      - name: brand_url
        label: Header Logo Link URL
        type: text
        required: false
      - name: search_placeholder
        label: Search Placeholder Text
        type: text
        required: false
      - name: featured_cards_eyebrow
        label: Featured Cards Eyebrow Text
        type: text
        required: false
      - name: featured_cards_title
        label: Featured Cards Heading
        type: text
        required: false
      - name: featured_cards_subtitle
        label: Featured Cards Description
        type: text
        required: false
      - name: content_eyebrow_font_size
        label: Content Eyebrow Font Size
        type: text
        required: false
        description: CSS font-size value (e.g., 0.72rem or 12px) used on prose, poetry, essays, projects, and achievements listing cards.
      - name: footer_heading
        label: Footer Heading
        type: text
        required: false
      - name: footer_review_url
        label: Footer Review Link URL
        type: text
        required: false
      - name: footer_note
        label: Footer Note
        type: text
        required: false
      - name: contact_email
        label: Contact Email
        type: text
        required: false
      - name: location
        label: Location
        type: text
        required: false
      - name: header_links
        label: Header Navigation Links
        type: object
        list: true
        addLabel: "+header navigation link"
        required: false
        fields:
          - name: label
            label: Header Name
            type: text
          - name: url
            label: Header Link
            type: text
      - name: social_links
        label: Footer Social Links
        type: object
        list: true
        addLabel: "+social link"
        required: false
        fields:
          - name: label
            label: Social Name
            type: text
          - name: url
            label: Social Link
            type: text
