site_title: Anshuman Pandey
site_tagline: Writing portfolio
contact_email: thisisanshumanp@gmail.com
location: Delhi, India
social_links:
  - label: LinkedIn
    url: https://www.linkedin.com/in/anshuman-pandey-b33362378
