site_title: Anshuman3kdka
site_tagline: I write essays, fiction, and poetry. Usually about literature,
  occasionally about why most of it fails. Currently a student, open to work
  that doesn't require me to use the word 'synergy.'
brand_url: https://www.anshuman3kdka.in
search_placeholder: Search essays, prose, projects, and achievements
featured_cards_eyebrow: Featured Cards
featured_cards_title: Things that got finished
featured_cards_subtitle: Visit my latest works
content_eyebrow_font_size: 0.72rem
analytics:
  enabled: false
  provider: plausible
  domain: www.anshuman3kdka.in
  script_src: https://plausible.io/js/script.js
footer_heading: Leave a review :)
footer_review_url: https://tally.so/r/rjlA4v
footer_note: Built between deadlines
contact_email: thisisanshumanp@gmail.com
location: Delhi, India
header_links:
  - label: Home
    url: /
  - label: About
    url: /about/
  - label: Essays
    url: /essays/
  - label: Creative
    url: /creative/
  - label: Projects
    url: /projects/
  - label: Contact
    url: /contact/
  - label: Resume
    url: /resume/
  - label: Achievements
    url: /achievements/
social_links:
  - label: LinkedIn
    url: https://www.linkedin.com/in/anshuman-pandey-b33362378
