site_title: Anshuman3kdka
site_tagline: Writing portfolio
site_description: Anshuman3kdka — essays, projects, and creative technology.
brand_url: /
search_placeholder: Search essays, prose, projects, and achievements
footer_heading: Let’s connect
footer_note: Built between deadlines
contact_email: thisisanshumanp@gmail.com
location: Delhi, India
